# Generated by Django 5.1.1 on 2024-09-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_upload',
            name='type',
            field=models.CharField(blank=True),
        ),
    ]
